apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "node"
  namespace: "default"
  labels:
    app: "node"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "node"
  template:
    metadata:
      labels:
        app: "node"
    spec:
      containers:
      - name: "app"
        image: "us-central1-docker.pkg.dev/gcp-jenkins-terraform/pythonapp/app:latest"
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "node-hpa-i4a0"
  namespace: "default"
  labels:
    app: "node"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "node"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: node
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080